// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ1BmKgHMLYfLC4iVtUdDT_xpXvlB9fyE',
    appId: '1:368342408622:web:5651752868cc9200d3fc3f',
    messagingSenderId: '368342408622',
    projectId: 'flutterproject-74261',
    authDomain: 'flutterproject-74261.firebaseapp.com',
    storageBucket: 'flutterproject-74261.firebasestorage.app',
    measurementId: 'G-2HRPX7MP6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8fDEnc7Jar1vomEbrQ1Ek3ENuwQRxp7Q',
    appId: '1:368342408622:android:fdf0192779877324d3fc3f',
    messagingSenderId: '368342408622',
    projectId: 'flutterproject-74261',
    storageBucket: 'flutterproject-74261.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTQvPxgpGbkSPdJF8dl54iVuVsUyG8xjQ',
    appId: '1:368342408622:ios:c341afa5ed79d69dd3fc3f',
    messagingSenderId: '368342408622',
    projectId: 'flutterproject-74261',
    storageBucket: 'flutterproject-74261.firebasestorage.app',
    iosBundleId: 'com.example.projectq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTQvPxgpGbkSPdJF8dl54iVuVsUyG8xjQ',
    appId: '1:368342408622:ios:c341afa5ed79d69dd3fc3f',
    messagingSenderId: '368342408622',
    projectId: 'flutterproject-74261',
    storageBucket: 'flutterproject-74261.firebasestorage.app',
    iosBundleId: 'com.example.projectq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ1BmKgHMLYfLC4iVtUdDT_xpXvlB9fyE',
    appId: '1:368342408622:web:693509a6c6965f09d3fc3f',
    messagingSenderId: '368342408622',
    projectId: 'flutterproject-74261',
    authDomain: 'flutterproject-74261.firebaseapp.com',
    storageBucket: 'flutterproject-74261.firebasestorage.app',
    measurementId: 'G-0KMM5WSC9R',
  );
}
